TOKENIZERS_PARALLELISM=false OMP_NUM_THREADS=1 torchrun --nproc_per_node=3 train_1.py \
    --model_name_or_path "Qwen/Qwen2.5-3B" \
    --num_train_epochs 3 \
    --learning_rate 5e-4 \
    --output_dir "./output" \
    --train_file "/root/data/ChID/processed/train.json" \
    --eval_file "/root/data/ChID/processed/dev.json" \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --save_steps 500 \
    --logging_steps 50\
    --fp16
